import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BannerSNAMolecule from "@/components/molecules/header/bannerSNA.molecule";
import InfoSNAMolecule from "@/components/molecules/footer/infoSNA.molecule";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <BannerSNAMolecule bannerTitle="SNA GLITZZ" />
      <body className="min-h-full flex flex-col">{children}</body>
      <InfoSNAMolecule />
    </html>
  );
}
